.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SPACESHOOTER" "1" "August 2010" "" ""
.
.SH "NAME"
\fBspaceshooter\fR \- 2D old\-school space shooter game
.
.SH "SYNOPSIS"
\fBspaceshooter\fR
.
.SH "DESCRIPTION"
SpaceShooter is an old\-school space shooter game in 2D, written using Allegro library, and licensed under GPLv3\.
.
.P
You play as the pilot of a spaceship who has the mission to destroy every hostile enemy\.
.
.SH "CONTROLS"
Here are the controls for the spaceship
.
.IP "\(bu" 4
Move the spaceship with mouse
.
.IP "\(bu" 4
Fire with mouse left button
.
.IP "\(bu" 4
Pause the game with P
.
.IP "\(bu" 4
Take a screenshot with S
.
.IP "\(bu" 4
Show controls with H
.
.IP "\(bu" 4
Exit the game with ESC
.
.IP "" 0
.
.SH "SCORE"
The scores are calculated as follows
.
.IP "\(bu" 4
+5 points for enemy hits
.
.IP "\(bu" 4
\-1 point for enemy survival
.
.IP "" 0
.
.SH "CONFIGURATION"
SpaceShooter will read the file \'$HOME/\.SpaceShooter/config\', and may set the following boolean variables:
.
.IP "\(bu" 4
\fBdebug [0|1]\fR Enable/disable debug mode\.
.
.IP "\(bu" 4
\fBdisable_audio [0|1]\fR Disable audio (set volume to 0)\.
.
.IP "\(bu" 4
\fBshow_fps [0|1]\fR Show FPS during game\.
.
.IP "\(bu" 4
\fBfullscreen [0|1]\fR Enable/disable fullscreen mode\.
.
.IP "\(bu" 4
\fBstart_timeout [TIMEOUT]\fR Set timeout seconds on start (default 3)
.
.IP "" 0
.
.SH "DEPENDENCIES"
SpaceShooter, to properly run, depends upon Allegro library\. In addition Allegro development files are needed to compile this game\.
.
.P
You can find all the files and additional information at \fB<http://www\.talula\.demon\.co\.uk/allegro>\fR
.
.SH "INSTALLATION"
SpaceShooter is distributed as source code\. Install with:
.
.IP "" 4
.
.nf

$ git clone git://github\.com/AlexBio/SpaceShooter\.git
$ cd SpaceShooter
$ \./bootstrap
$ \./configure
$ make
# make install
.
.fi
.
.IP "" 0
.
.P
Debian (\.deb) packages for i386 and amd64 architectures and source tarball are also available at \fB<http://github\.com/AlexBio/SpaceShooter/downloads>\fR
.
.SH "BUGS"
Please report any bugs or feature requests to GitHub issues tracker at \fB<http://github\.com/AlexBio/SpaceShooter/issues>\fR\.
.
.SH "SUPPORT"
You can look for information at:
.
.IP "\(bu" 4
Homepage \fB<http://ghedini\.co\.cc/SpaceShooter>\fR
.
.IP "\(bu" 4
GitHub repository \fB<http://github\.com/AlexBio/SpaceShooter>\fR
.
.IP "" 0
.
.SH "AUTHOR"
Alessandro Ghedini, \fIal3xbio@gmail\.com\fR
.
.SH "COPYRIGHT"
Copyright (C) 2010 Alessandro Ghedini \fB<http://ghedini\.co\.cc>\fR
.
.P
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation\.
