.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SPACESHOOTER" "6" "October 2011" "" ""
.
.SH "NAME"
\fBspaceshooter\fR \- old\-school space shooter game in 2D
.
.SH "SYNOPSIS"
\fBspaceshooter\fR
.
.SH "DESCRIPTION"
\fBspaceshooter\fR is an arcade style, scrolling space shooter in 2D\. Your job is to pilot a spaceship against the flow of many hostile enemies, killing as many as possible\.
.
.SH "CONTROLS"
You can move the spaceship with the \fImouse\fR, fire with the mouse \fIleft button\fR, pause the game with \fIP\fR, and exit the game with \fIESC\fR\.
.
.SH "SCORE"
The player gets \fI+5\fR points for every destroyed enemy and \fI\-1\fR point for every escaped enemy\.
.
.SH "FILES"
\fB~/\.config/spaceshooter/record\fR
.
.P
\~\~\~\~\~\~ Where your record is stored\.
.
.SH "AUTHOR"
Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.SH "COPYRIGHT"
Copyright (C) 2011 Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.P
This program is released under the 3 clause BSD license\.
