.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SPACESHOOTER" "6" "December 2010" "" ""
.
.SH "NAME"
\fBspaceshooter\fR \- old\-school space shooter game in 2D
.
.SH "SYNOPSIS"
\fBspaceshooter [\-d] [\-f] [\-a]\fR
.
.SH "DESCRIPTION"
\fBspaceshooter\fR is a score attack game in which the player has to pilot a spaceship against the flow of many hostile enemies\. The goal is obviously to destroy them all\.
.
.SH "OPTIONS"
\fB\-d\fR
.
.br
\~\~\~Enable debug mode
.
.P
\fB\-f\fR
.
.br
\~\~\~Enable fullscreen
.
.P
\fB\-a\fR
.
.br
\~\~\~Disable audio
.
.SH "CONTROLS"
You can move the spaceship with \fImouse\fR, fire with mouse \fIleft button\fR, pause the game with \fIP\fR, take a screenshot with \fIS\fR, show controls with \fIH\fR and exit the game with \fIESC\fR\.
.
.SH "SCORE"
The player gets \fI+5\fR points if he destroies an enemy and \fI\-1\fR point when an enemy escapes\.
.
.P
The score record is stored in the <~/\.SpaceShooter/record> file\.
.
.SH "CONFIGURATION"
SpaceShooter will read the file <~/\.SpaceShooter/config>, and may set the following boolean variables:
.
.P
\fBdebug [0|1]\fR
.
.br
\~\~\~Enable/disable debug mode\.
.
.P
\fBdisable_audio [0|1]\fR
.
.br
\~\~\~Disable audio (set volume to 0)\.
.
.P
\fBfullscreen [0|1]\fR
.
.br
\~\~\~Enable/disable fullscreen mode\.
.
.SH "DEPENDENCIES"
SpaceShooter, to properly run, depends upon Allegro library\. In addition Allegro development files are needed to compile this game\.
.
.P
You can find all the files and additional information at \fB<http://www\.talula\.demon\.co\.uk/allegro>\fR
.
.SH "BUGS"
Please report any bugs or feature requests to GitHub issues tracker at \fB<http://github\.com/AlexBio/SpaceShooter/issues>\fR\.
.
.SH "SUPPORT"
You can look for information at:
.
.IP "\(bu" 4
Homepage \fB<http://ghedini\.co\.cc/SpaceShooter>\fR
.
.IP "\(bu" 4
GitHub repository \fB<http://github\.com/AlexBio/SpaceShooter>\fR
.
.IP "" 0
.
.SH "INSTALL"
See \fBREADME\fR for installation\.
.
.SH "AUTHOR"
Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.SH "COPYRIGHT"
Copyright (C) 2010 Alessandro Ghedini \fIal3xbio@gmail\.com\fR
.
.P
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation (see \fBLICENSE\fR)\.
